force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <description>Person who plays soccer</description>
    <label>Player</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>is active?</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The team, player is related to</description>
    <inlineHelpText>The team, player is related to</inlineHelpText>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Team where player makes his duties</description>
    <label>Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PlayerBonusBatch.cls
global class PlayerBonusBatch implements Database.Batchable<sObject> {
    private map<Id, Integer> teamIdWinsMap;
    private Set<Id> idSet;
    private Integer base;
    global PlayerBonusBatch(map<Id, Integer> tmpMap, Integer tmpBase){
        teamIdWinsMap=tmpMap;
        idSet=teamIdWinsMap.keySet();
        base=tmpBase;
    }
    global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'SELECT Id, Bonus__c, Team__c FROM Player__c WHERE IsActive__c=True and  Team__c=:idSet';
        //SoccerDAO.getTeamWins(matchList);
        return Database.getQueryLocator(query);
    }
     
    global void execute(Database.BatchableContext BC, List<Player__c> playersList) {
        for(Player__c tmp : playersList) {        
            tmp.Bonus__c = base*teamIdWinsMap.get(tmp.Team__c);
        }
        try {
            update playersList;
        } catch(Exception e) {
            System.debug(e);
        }
    }   
     
    global void finish(Database.BatchableContext BC) {
        // execute any post-processing operations like sending email
    }
}