force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <description>Soccer match</description>
    <label>Match</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Match</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Home_Team__c.field-meta.xml
<CustomField>
    <fullName>Home_Team__c</fullName>
    <description>Home Team</description>
    <label>Home Team</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team must have 11 active players</errorMessage>
        <filterItems>
            <field>Team__c.Total_Active_Players__c</field>
            <operation>greaterOrEqual</operation>
            <value>11</value>
        </filterItems>
        <infoMessage>Team must have 11 active players</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Match</relationshipLabel>
    <relationshipName>Match</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>&apos;0:0&apos;</defaultValue>
    <description>Represents Home Team vs Visitor scores (e.g. &apos;1:2&apos; means Visitor won)</description>
    <label>Score</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Start_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Start_DateTime__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>Beginning of the match</description>
    <label>Start DateTime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Visitors__c.field-meta.xml
<CustomField>
    <fullName>Visitors__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Visitor team</description>
    <label>Visitor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team must have 11 active players</errorMessage>
        <filterItems>
            <field>Team__c.Total_Active_Players__c</field>
            <operation>greaterOrEqual</operation>
            <value>11</value>
        </filterItems>
        <infoMessage>Team must have 11 active players</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Match (Visitor)</relationshipLabel>
    <relationshipName>Match1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <description>Person who plays soccer</description>
    <label>Player</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Email; 
should be unique.</description>
    <label>Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Player__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>is active?</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The team, player is related to</description>
    <inlineHelpText>The team, player is related to</inlineHelpText>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Team where player makes his duties</description>
    <label>Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Played_Home_Matches_Count__c.field-meta.xml
<CustomField>
    <fullName>Played_Home_Matches_Count__c</fullName>
    <description>Define number of games with scores that team played at home</description>
    <label>Played Home Matches Count</label>
    <summaryForeignKey>Match__c.Home_Team__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Total_Active_Players__c.field-meta.xml
<CustomField>
    <fullName>Total_Active_Players__c</fullName>
    <description>total number of active players</description>
    <label>Total Active Players</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Total_Wins__c.field-meta.xml
<CustomField>
    <fullName>Total_Wins__c</fullName>
    <defaultValue>0</defaultValue>
    <description>total wins of the team</description>
    <label>Total Wins</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SoccerDAOTest.cls
@isTest //(SeeAllData=True)
public with sharing class SoccerDAOTest {
    @testSetup static void setup() {
        // Create common test Teams
        List<Team__c> testTeam = new List<Team__c>();
        for(Integer i=0;i<2;i++) {
            testTeam.add(new Team__c(Name ='Team_'+i, Total_Active_Players__c =13));
        }
        testTeam.get(0).Total_Wins__c=2;
        insert testTeam;

        // Create common test Players
        List<Player__c> testPlayer = new List<Player__c>();
        Integer k=0;
        for (Integer j=0;j<testTeam.size();j++) {
            for(Integer i=0;i< 13;i++) {
                testPlayer.add(new Player__c(Name ='Player_'+k, Email__c ='Player_'+k+'@ukr.net', IsActive__c =True, Team__c=testTeam.get(j).id));
                k++;
            } 
        }             
        upsert testPlayer;

        // Create common test Match
        List<Match__c> testMatch = new List<Match__c>();
        Integer n=0, m=1;
        for(Integer i=0;i<3;i++) {
            testMatch.add(new Match__c(Name ='TestMatch_'+i, Start_DateTime__c =DateTime.now()+i, Home_Team__c =testTeam.get(n).Id, Visitors__c =testTeam.get(m).Id, Score__c ='00:00'));
            n = n<testTeam.size() ? n++ : 0;
            m = m<testTeam.size() ? m++ : 0;
        }
        testMatch.get(0).Score__c= '00:01';
        testMatch.get(1).Score__c= '02:00';
        upsert testMatch; 
        
        system.debug(System.LoggingLevel.DEBUG, testTeam);
        system.debug(System.LoggingLevel.DEBUG, testPlayer);
        system.debug(System.LoggingLevel.DEBUG, testMatch);            
    }
    @isTest public static void getTeamsByIds(){
        Set<Id> idSet= new Set<Id>();
        for (Team__c tmp : [SELECT id FROM Team__c LIMIT 2]) {
            idSet.add(tmp.id);
        }
        Test.startTest();
        List<Team__c> tmp= SoccerDAO.getTeamsByIds(idSet);
        Test.stopTest();

        System.assertEquals([SELECT id, Name, Total_Wins__c, Total_Active_Players__c, Played_Home_Matches_Count__c FROM Team__c WHERE id =: idSet], tmp, 'getTeamsByIds valid');
    }
    @isTest public static void getActivePlayers(){
        Test.startTest();
        List<Player__c> tmp= SoccerDAO.getActivePlayers(10,4);
        Test.stopTest();

        System.assertEquals([SELECT id, Name, Email__c, IsActive__c, Team__c FROM Player__c WHERE IsActive__c=true ORDER BY Name LIMIT: 10 OFFSET: 4], tmp, 'getActivePlayers valid');
    }    
    @isTest public static void getMostWinnerTeam(){  
        Map<id, Integer> teamWinsMap = SoccerDAO.getTeamWins([SELECT id, score__c, Home_Team__c, Visitors__c FROM Match__c]);
        integer max =0;
        id tmpId;
        for (id tmp : teamWinsMap.keySet()) {
            if (teamWinsMap.get(tmp)>=max) {
               max= teamWinsMap.get(tmp);
               tmpId = tmp;
            }
        }
        Team__c retTeam = new Team__c(id=tmpId);

        Test.startTest();
        Team__c tmp= SoccerDAO.getMostWinnerTeam(); 
        Test.stopTest();

        System.assertEquals(retTeam, tmp, 'getMostWinnerTeam valid');    
    }
    @isTest public static void getWonMatchesCountByTeamId(){
        List<Team__c> teamList= new List<Team__c>([SELECT id, Total_Wins__c FROM Team__c]);
        Id tmpId = teamList.get(0).Id;
        Integer retTmp =(Integer)teamList.get(0).Total_Wins__c;

        Test.startTest();
        Integer tmp = SoccerDAO.getWonMatchesCountByTeamId(tmpId);
        Test.stopTest();

        System.assertEquals(retTmp,tmp,'getWonMatchesCountByTeamId valid');
    }
    @isTest public static void getTeamsWithPlayerNumber(){
        Set<Id> idSet= new Set<Id>{};
        for (Team__c tmp : new List<Team__c>([SELECT id FROM Team__c])){
            idSet.add(tmp.id);
        }
        Map<Id,Integer> teamActivePlayersCount = new Map<Id,Integer>();
        for (AggregateResult tmpAggrResalt :  [select count(id) countID, team__c from player__c where isActive__c=true and team__c=:idSet GROUP BY team__c]) {
            teamActivePlayersCount.put((Id)tmpAggrResalt.get('team__c'), (integer)tmpAggrResalt.get('countID'));        
        }
        
        Test.startTest();
        Map<Id, Integer> tmp= SoccerDAO.getTeamsWithPlayerNumber(idSet);
        Test.stopTest();

        System.assertEquals(teamActivePlayersCount,tmp,'getTeamsWithPlayerNumber valid');
    }
    @isTest public static void getTeamStatistics(){
        Set<Id> idSet= new Set<Id>();
        Integer playerCount=0 , average=0;
        for (Team__c tmp : [SELECT id, Total_Active_Players__c FROM Team__c ]) {
            idSet.add(tmp.id);
        }

        Map<Id, Integer> teamWithPlayer = SoccerDAO.getTeamsWithPlayerNumber(idSet);
        for (id tmp : teamWithPlayer.keySet()) {
            average=average+teamWithPlayer.get(tmp);   
            playerCount++;          
        }
        Integer retTmp =(Integer)average/playerCount;

        Test.startTest();
        Integer statTmp = SoccerDAO.getTeamStatistics(idSet);
        Test.stopTest();

        System.assertEquals(retTmp,statTmp,'getTeamStatistics valid');
    }
    @isTest public static void getTeamWithMostScores(){

        List<Team__c> teamList = new List<Team__c>([SELECT id FROM Team__c]);
        List<Match__c> matchList = new List<Match__c>([SELECT id, score__c, Home_Team__c, Visitors__c FROM Match__c]);
        Integer score=0, max=0;
        Team__c retTeam;
        for (Team__c tmpTeam : teamList) {
            score=0;
            for (Match__c tmpMatch: matchList){
                Integer a = Integer.valueOf(tmpMatch.score__c.substringBefore(':'));
                Integer b = Integer.valueOf(tmpMatch.score__c.substringAfter(':'));
                if((a>b && tmpMatch.Home_Team__c==tmpTeam.id)||(a<b && tmpMatch.Visitors__c==tmpTeam.id)){
                    score=score+2;
                }
                if(a==b && (tmpMatch.Home_Team__c==tmpTeam.id || tmpMatch.Visitors__c==tmpTeam.id)){
                    score=score+1;
                }
            }
            if (max<score) {
                max=score;
                retTeam=tmpTeam;
            }
        }

        Test.startTest();
        Team__c tmp= SoccerDAO.getTeamWithMostScores();
        Test.stopTest();
        
        System.assertEquals(retTeam,tmp,'getTeamWithMostScores valid');
    }
    @isTest public static void getTeamWins(){
        Map<Id, Integer> resTmp= new Map<Id, Integer>();
        Set<Id> matchIdSet= new Set<Id>();
        List<Match__c> matchList = new List<Match__c>([SELECT id, score__c, Home_Team__c, Visitors__c FROM Match__c LIMIT 2]);

        for (Match__c tmp: matchList){
            matchIdSet.add(tmp.id);
            if (!resTmp.containsKey(tmp.Home_Team__c))  {    resTmp.put(tmp.Home_Team__c,0);}
            if (!resTmp.containsKey(tmp.Visitors__c))   {    resTmp.put(tmp.Visitors__c,0);}

            Integer a = Integer.valueOf(tmp.score__c.substringBefore(':'));
            Integer b = Integer.valueOf(tmp.score__c.substringAfter(':'));

            if(a>b){
                if (resTmp.containsKey(tmp.Home_Team__c)){
                    resTmp.put(tmp.Home_Team__c,resTmp.get(tmp.Home_Team__c)+1);
                }
            }
            if(a<b){
                if (resTmp.containsKey(tmp.Visitors__c)){
                    resTmp.put(tmp.Visitors__c,resTmp.get(tmp.Visitors__c)+1);
                }
            }
        }
        
        Test.startTest();
        Map<Id, Integer> tmpMap= SoccerDAO.getTeamWins([SELECT id, score__c, Home_Team__c, Visitors__c FROM Match__c WHERE id=:matchIdSet]);
        Test.stopTest();

        System.assertEquals(resTmp,tmpMap,'getTeamWins valid');
    }
}