force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <description>Soccer match</description>
    <label>Match</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Match</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Home_Team__c.field-meta.xml
<CustomField>
    <fullName>Home_Team__c</fullName>
    <description>Home Team</description>
    <label>Home Team</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team must have 11 active players</errorMessage>
        <filterItems>
            <field>Team__c.Total_Active_Players__c</field>
            <operation>greaterOrEqual</operation>
            <value>11</value>
        </filterItems>
        <infoMessage>Team must have 11 active players</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Match</relationshipLabel>
    <relationshipName>Match</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>&apos;0:0&apos;</defaultValue>
    <description>Represents Home Team vs Visitor scores (e.g. &apos;1:2&apos; means Visitor won)</description>
    <label>Score</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Start_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Start_DateTime__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>Beginning of the match</description>
    <label>Start DateTime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Visitors__c.field-meta.xml
<CustomField>
    <fullName>Visitors__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Visitor team</description>
    <label>Visitor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team must have 11 active players</errorMessage>
        <filterItems>
            <field>Team__c.Total_Active_Players__c</field>
            <operation>greaterOrEqual</operation>
            <value>11</value>
        </filterItems>
        <infoMessage>Team must have 11 active players</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Match (Visitor)</relationshipLabel>
    <relationshipName>Match1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Winner__c.field-meta.xml
<CustomField>
    <fullName>Winner__c</fullName>
    <description>Represents Name of winner team or &apos;Draw&apos; if score is equal</description>
    <formula>IF( VALUE(LEFT( Score__c ,FIND(&apos;:&apos;,Score__c )-1))&gt;VALUE(RIGHT( Score__c ,FIND(&apos;:&apos;,Score__c )-1)),  Home_Team__r.Name ,  IF( VALUE(LEFT( Score__c ,FIND(&apos;:&apos;,Score__c )-1))&lt;VALUE(RIGHT( Score__c ,LEN(Score__c)-FIND(&apos;:&apos;,Score__c))),  Visitors__r.Name , &apos;Draw&apos;) )</formula>
    <inlineHelpText>Represents Name of winner team or &apos;Draw&apos; if score is equal</inlineHelpText>
    <label>Winner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <description>Person who plays soccer</description>
    <label>Player</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Email; 
should be unique.</description>
    <label>Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Player__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>is active?</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The team, player is related to</description>
    <inlineHelpText>The team, player is related to</inlineHelpText>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Team where player makes his duties</description>
    <label>Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Total_Active_Players__c.field-meta.xml
<CustomField>
    <fullName>Total_Active_Players__c</fullName>
    <description>total number of active players</description>
    <label>Total Active Players</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Total_Wins__c.field-meta.xml
<CustomField>
    <fullName>Total_Wins__c</fullName>
    <defaultValue>0</defaultValue>
    <description>total wins of the team</description>
    <label>Total Wins</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MatchTriggerTest.cls
@isTest //(SeeAllData=True)
public with sharing class MatchTriggerTest {
    
    @testSetup static void setup() {
        // Create common test Teams
        List<Team__c> testTeam = new List<Team__c>();
        for(Integer i=0;i<2;i++) {
            testTeam.add(new Team__c(Name ='Team_'+i, Total_Active_Players__c =13));
        }
        insert testTeam;

        // Create common test Players
        List<Player__c> testPlayer = new List<Player__c>();
        Integer k=0;
        for (Integer j=0;j<testTeam.size();j++) {
            for(Integer i=0;i<=12;i++) {
                testPlayer.add(new Player__c(Name ='Player_'+k, Email__c ='Player_'+k+'@ukr.net', IsActive__c =True, Team__c=testTeam.get(j).id));
                k++;
            } 
        }             
        upsert testPlayer;

        // Create common test Match
        List<Match__c> testMatch = new List<Match__c>();
        Integer n=0, m=1;
        for(Integer i=0;i<3;i++) {
            testMatch.add(new Match__c(Name ='TestMatch_'+i, Start_DateTime__c =DateTime.now()+i, Home_Team__c =testTeam.get(n).Id, Visitors__c =testTeam.get(m).Id, Score__c ='00:00'));
            n = n<testTeam.size() ? n++ : 0;
            m = m<testTeam.size() ? m++ : 0;
        }
        upsert testMatch; 
        
        system.debug(System.LoggingLevel.DEBUG, testTeam);
        system.debug(System.LoggingLevel.DEBUG, testPlayer);
        system.debug(System.LoggingLevel.DEBUG, testMatch);            
    }
   @isTest public static void teamWinsUpdate(){
        //Set<Id> idsSet = new Set<Id>{'a0B090000029AQWEA2','a0B090000029AQgEAM'};
        List<Match__c> matchList = new List<Match__c>([SELECT id, Winner__c, Score__c, Home_Team__c, Visitors__c FROM Match__c LIMIT 2]);


        Test.startTest();
        Map<Id, Integer> tmpTeam= SoccerDAO.getTeamWins(matchList);
        List<Team__C> tmpTeamList = new List<Team__C>();
        for (Id tmp : tmpTeam.keySet()) {
            tmpTeamList.add(new Team__c(Id=tmp, Total_Wins__c=tmpTeam.get(tmp)));
        }
        update tmpTeamList;
        Test.stopTest();
   }
}