force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <description>Soccer match</description>
    <label>Match</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Match</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Home_Team__c.field-meta.xml
<CustomField>
    <fullName>Home_Team__c</fullName>
    <description>Home Team</description>
    <label>Home Team</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team must have 11 active players</errorMessage>
        <filterItems>
            <field>Team__c.Total_Active_Players__c</field>
            <operation>greaterOrEqual</operation>
            <value>11</value>
        </filterItems>
        <infoMessage>Team must have 11 active players</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Match</relationshipLabel>
    <relationshipName>Match</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>&apos;0:0&apos;</defaultValue>
    <description>Represents Home Team vs Visitor scores (e.g. &apos;1:2&apos; means Visitor won)</description>
    <label>Score</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Visitors__c.field-meta.xml
<CustomField>
    <fullName>Visitors__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Visitor team</description>
    <label>Visitor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team must have 11 active players</errorMessage>
        <filterItems>
            <field>Team__c.Total_Active_Players__c</field>
            <operation>greaterOrEqual</operation>
            <value>11</value>
        </filterItems>
        <infoMessage>Team must have 11 active players</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Match (Visitor)</relationshipLabel>
    <relationshipName>Match1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <description>Person who plays soccer</description>
    <label>Player</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Email; 
should be unique.</description>
    <label>Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Player__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>is active?</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The team, player is related to</description>
    <inlineHelpText>The team, player is related to</inlineHelpText>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Team where player makes his duties</description>
    <label>Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Played_Home_Matches_Count__c.field-meta.xml
<CustomField>
    <fullName>Played_Home_Matches_Count__c</fullName>
    <description>Define number of games with scores that team played at home</description>
    <label>Played Home Matches Count</label>
    <summaryForeignKey>Match__c.Home_Team__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Total_Active_Players__c.field-meta.xml
<CustomField>
    <fullName>Total_Active_Players__c</fullName>
    <description>total number of active players</description>
    <label>Total Active Players</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Total_Wins__c.field-meta.xml
<CustomField>
    <fullName>Total_Wins__c</fullName>
    <defaultValue>0</defaultValue>
    <description>total wins of the team</description>
    <label>Total Wins</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SoccerDAO.cls
public with sharing class SoccerDAO {
    public List<Team__c> getTeamsByIds(set<Id> teamIds) {
        return new List<Team__c>([SELECT id, Name, Total_Wins__c, Total_Active_Players__c, Played_Home_Matches_Count__c FROM Team__c WHERE id =: teamIds]);
    }
    public List<Player__c> getActivePlayers(Integer limitNumber, Integer offsetNumber){
        return new List<Player__c>([SELECT id, Name, Email__c, IsActive__c, Team__c FROM Player__c WHERE IsActive=true ORDER BY Name LIMIT: limitNumber OFFSET: offsetNumber]);
    }  
    public Team__c getMostWinnerTeam(){
        return new Team__c();
    }
    public Integer getWonMatchesCountByTeamId(){
        
        return null;
    }   
    public Map<Id, Integer> getTeamsWithPlayerNumber(Set<Id> teamIds){

        return null;
    }
    public Integer getTeamStatistics(Set<Id> teamIds){

        return null;
    }
    public Team__c getTeamWithMostScores(){

        return null;
    } 
    public Map<Id, Integer> getTeamWins(List<Match__c> matchList){
        List<id> teamList = new List<id>([SELECT id FROM Team__c]);
        Map<id, Integer> teamWinsMap = new Map<id, Integer>(teamList);
        teamWinsMap.putAll(teamList,'0');
        for (Match__c tmp: matchList){
            Integer a = Integer.valueOf(left(String(tmp.score__c).indexOf(':')-1));
            Integer b = Integer.valueOf(right(String(tmp.score__c).indexOf(':')-1));
            switch on a {
                when  a>b{
                    if (teamWinsMap.containsKey(tmp.Home_Team__c)){
                        teamWinsMap.put(teamWinsMap.get(tmp.Home_Team__c)+1);
                    }
                }
                when a<b{
                    if (teamWinsMap.containsKey(tmp.Visitors__c)){
                        teamWinsMap.put(teamWinsMap.get(tmp.Visitors__c)+1);
                    }
                }
            }          
        }
        return teamWinsMap;
    }
}