force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <description>Soccer match</description>
    <label>Match</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Match</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Home_Team__c.field-meta.xml
<CustomField>
    <fullName>Home_Team__c</fullName>
    <description>Home Team</description>
    <label>Home Team</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team must have 11 active players</errorMessage>
        <filterItems>
            <field>Team__c.Total_Active_Players__c</field>
            <operation>greaterOrEqual</operation>
            <value>11</value>
        </filterItems>
        <infoMessage>Team must have 11 active players</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Match</relationshipLabel>
    <relationshipName>Match</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>&apos;0:0&apos;</defaultValue>
    <description>Represents Home Team vs Visitor scores (e.g. &apos;1:2&apos; means Visitor won)</description>
    <label>Score</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Start_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Start_DateTime__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>Beginning of the match</description>
    <label>Start DateTime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Visitors__c.field-meta.xml
<CustomField>
    <fullName>Visitors__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Visitor team</description>
    <label>Visitor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team must have 11 active players</errorMessage>
        <filterItems>
            <field>Team__c.Total_Active_Players__c</field>
            <operation>greaterOrEqual</operation>
            <value>11</value>
        </filterItems>
        <infoMessage>Team must have 11 active players</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Match (Visitor)</relationshipLabel>
    <relationshipName>Match1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <description>Person who plays soccer</description>
    <label>Player</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Email; 
should be unique.</description>
    <label>Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Player__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>is active?</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The team, player is related to</description>
    <inlineHelpText>The team, player is related to</inlineHelpText>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Team where player makes his duties</description>
    <label>Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Total_Active_Players__c.field-meta.xml
<CustomField>
    <fullName>Total_Active_Players__c</fullName>
    <description>total number of active players</description>
    <label>Total Active Players</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SoccerServiceTest.cls
@isTest 
public with sharing class SoccerServiceTest {

    @testSetup static void setup() {
        // Create common test Teams
        List<Team__c> testTeam = new List<Team__c>();
        for(Integer i=0;i<2;i++) {
            testTeam.add(new Team__c(Name ='Team_'+i, Total_Active_Players__c =13));
        }
        insert testTeam;

        // Create common test Players
        List<Player__c> testPlayer = new List<Player__c>();
        Integer k=0;
        for (Integer j=0;j<testTeam.size();j++) {
            for(Integer i=0;i<=12;i++) {
                testPlayer.add(new Player__c(Name ='Player_'+k, Email__c ='Player_'+k+'@ukr.net', IsActive__c =True, Team__c=testTeam.get(j).id));
                k++;
            } 
        }             
        upsert testPlayer;

        // Create common test Match
        List<Match__c> testMatch = new List<Match__c>();
        Integer n=0, m=1;
        for(Integer i=0;i<3;i++) {
            testMatch.add(new Match__c(Name ='TestMatch_'+i, Start_DateTime__c =DateTime.now()+i, Home_Team__c =testTeam.get(n).Id, Visitors__c =testTeam.get(m).Id, Score__c ='00:00'));
            n = n<testTeam.size() ? n++ : 0;
            m = m<testTeam.size() ? m++ : 0;
        }
        upsert testMatch; 
        
        system.debug(System.LoggingLevel.DEBUG, testTeam);
        system.debug(System.LoggingLevel.DEBUG, testPlayer);
        system.debug(System.LoggingLevel.DEBUG, testMatch);            
    }


    @isTest public static void createPlayer(){
        
        List<Player__c> playerList= new List<Player__c>([SELECT id, name, email__c, isActive__c, Team__c FROM Player__c]);
        Integer i =0;
        Map<SObjectField, Object> extraValues =new Map<SObjectField, Object>{Schema.sObjectType.Player__c.fields.getMap().get('IsActive__c')=> (Math.mod(i,2) == 0 ? true : false)};
        Integer old = ([SELECT id FROM Player__c]).size();
        
        Test.startTest();
        SoccerService.createPlayer('Player_'+playerList.size(), 'Player_'+playerList.size()+'@ukr.net', extraValues);
        Test.stopTest();
        
        Integer ret = ([SELECT id FROM Player__c]).size();
        
        System.assertEquals(old+1, ret,'createPlayer valid');
    }
    @isTest public static void arangeMatch(){
        List<Team__c> teamList= new List<Team__c>([SELECT id FROM Team__c]);
        Id home = teamList.get(0).Id;
        Id visit = teamList.get(1).Id;
        Datetime t = Datetime.now();
        
        Integer old = ([SELECT id FROM Match__c]).size();

        Test.startTest();
        SoccerService.arangeMatch(t,home,visit);
        Test.stopTest();

        Integer ret = ([SELECT id FROM Match__c]).size();
        
        System.assertEquals(old+1, ret,'arangeMatch valid');
    }
/*  @isTest public static void setScoreToMatches(){
       List<SoccerService.ScoreHelper> scores= new List<SoccerService.ScoreHelper>();
       scores.add(new SoccerService.ScoreHelper((Id)'a0B090000029AQgEAM',1,1));
       scores.add(SoccerService.ScoreHelper((Id)'a0B090000029AQWEA2',1,2));

       SoccerService.setScoreToMatches(scores);
    }*/
    @isTest public static void deactivatePlayers(){
        List<Id> playersIds= new List<Id>();
        for (PLayer__c tmp : [SELECT id FROM Player__c LIMIT 2]) {
            playersIds.add(tmp.id);
        }
        Integer old = ([SELECT id FROM Player__c WHERE isActive__c = true]).size();

        Test.startTest();
        SoccerService.deactivatePlayers(playersIds);
        Test.stopTest();

        Integer ret = ([SELECT id FROM Player__c WHERE isActive__c = true]).size();
        
        System.assertEquals(old-2, ret,'deactivatePlayers valid');
    }/* */
}