force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <description>Soccer match</description>
    <label>Match</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Match</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Previous_Match_Between_Teams_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Previous_Match_Between_Teams_Datetime__c</fullName>
    <description>Represents the date and time of the previous match between those teams.</description>
    <inlineHelpText>Represents the date and time of the previous match between those teams.</inlineHelpText>
    <label>Previous Match Between Teams Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Team where player makes his duties</description>
    <label>Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Total_Wins__c.field-meta.xml
<CustomField>
    <fullName>Total_Wins__c</fullName>
    <defaultValue>0</defaultValue>
    <description>total wins of the team</description>
    <label>Total Wins</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MatchTriggerHendler.cls
public with sharing class MatchTriggerHendler {
    public static void updatePreviousMatchDateTime(List<Match__c> matchList) {
        for (Match__c matchTmp : matchList) {
            matchTmp.Previous_Match_Between_Teams_Datetime__c= SoccerDAO.previousMatchDatetimeSet(matchTmp);
        }
    }
    public static void teamWinsUpdate(List<Match__c> matchList) {
        Map<Id, Integer> tmpTeam= SoccerDAO.getTeamWins(matchList);
        List<Team__C> tmpTeamList = new List<Team__C>();
        for (Id tmp : tmpTeam.keySet()) {
            tmpTeamList.add(new Team__c(Id=tmp, Total_Wins__c=tmpTeam.get(tmp)));
        }
        update tmpTeamList;
    }
}