force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <description>Soccer match</description>
    <label>Match</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Match</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Days_Left__c.field-meta.xml
<CustomField>
    <fullName>Days_Left__c</fullName>
    <description>Days left before the beginning of the match</description>
    <formula>IF((Start_DateTime__c -  NOW())&gt;=0,  Start_DateTime__c -  NOW() , 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Left</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Home_Team__c.field-meta.xml
<CustomField>
    <fullName>Home_Team__c</fullName>
    <description>Home Team</description>
    <label>Home Team</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team must have 11 active players</errorMessage>
        <filterItems>
            <field>Team__c.Total_Active_Players__c</field>
            <operation>greaterOrEqual</operation>
            <value>11</value>
        </filterItems>
        <infoMessage>Team must have 11 active players</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Match</relationshipLabel>
    <relationshipName>Match</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Previous_Match_Between_Teams_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Previous_Match_Between_Teams_Datetime__c</fullName>
    <description>Represents the date and time of the previous match between those teams.</description>
    <inlineHelpText>Represents the date and time of the previous match between those teams.</inlineHelpText>
    <label>Previous Match Between Teams Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>&apos;0:0&apos;</defaultValue>
    <description>Represents Home Team vs Visitor scores (e.g. &apos;1:2&apos; means Visitor won)</description>
    <label>Score</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Start_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Start_DateTime__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>Beginning of the match</description>
    <label>Start DateTime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Visitors__c.field-meta.xml
<CustomField>
    <fullName>Visitors__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Visitor team</description>
    <label>Visitor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team must have 11 active players</errorMessage>
        <filterItems>
            <field>Team__c.Total_Active_Players__c</field>
            <operation>greaterOrEqual</operation>
            <value>11</value>
        </filterItems>
        <infoMessage>Team must have 11 active players</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Match (Visitor)</relationshipLabel>
    <relationshipName>Match1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Winner__c.field-meta.xml
<CustomField>
    <fullName>Winner__c</fullName>
    <description>Represents Name of winner team or &apos;Draw&apos; if score is equal</description>
    <formula>IF( VALUE(LEFT( Score__c ,FIND(&apos;:&apos;,Score__c )-1))&gt;VALUE(RIGHT( Score__c ,FIND(&apos;:&apos;,Score__c )-1)),  Home_Team__r.Name ,  IF( VALUE(LEFT( Score__c ,FIND(&apos;:&apos;,Score__c )-1))&lt;VALUE(RIGHT( Score__c ,LEN(Score__c)-FIND(&apos;:&apos;,Score__c))),  Visitors__r.Name , &apos;Draw&apos;) )</formula>
    <inlineHelpText>Represents Name of winner team or &apos;Draw&apos; if score is equal</inlineHelpText>
    <label>Winner</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <description>Person who plays soccer</description>
    <label>Player</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Email; 
should be unique.</description>
    <label>Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Player__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>is active?</description>
    <label>IsActive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Player__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The team, player is related to</description>
    <inlineHelpText>The team, player is related to</inlineHelpText>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <description>Team where player makes his duties</description>
    <label>Team</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SoccerService.cls
public with sharing class SoccerService {
   
    public static void createPlayer(String name, String email, Map<SObjectField, Object> extraValues){
        Player__c retPlayer= new Player__c();
        retPlayer.Name=name;
        retPlayer.Email__c=email;
        retPlayer.Team__c=extraValues.get('Team__c');
        retPlayer.IsActive__c=extraValues.get('IsActive__c');
        try {
            insert retPlayer;
        } catch (DmlException e) {
            System.debug('A DML insert exception has occurred: ' + e.getMessage());
        }
    }

    public static void arangeMatch(DateTime dt, Id homeTeamId, Id visitorsTeamId){
        Match__c retMatch= new Match__c();
        retMatch.Start_DateTime__c=dt;
        retMatch.Home_Team__c=homeTeamId;
        retMatch.Visitors__c=visitorsTeamId;
        try {
            insert retMatch;
        } catch (DmlException e) {
            System.debug('A DML insert exception has occurred: ' + e.getMessage());
        }
    }
    public static void setScoreToMatches(List<ScoreHelper> scores){
        List<Match__c> retMatch= new List<Match__c>([SELECT id, Name, Start_DateTime__c, Home_Team__c, 
                                                            Visitors__c, Days_Left__c, Previous_Match_Between_Teams_Datetime__c, 
                                                            Score__c, Winner__c FROM Match__c WHERE id =: scores.matchId]);
        for (ScoreHelper tmp : scores) {
            retMatch.get(retMatch.indexOf(tmp.matchId)).Score__c=tmp.homeTeamScore+':'+tmp.visitorsTeamScore;
        }
        try {
            upsert retMatch;
        } catch (DmlException e) {
            System.debug('A DML upsert exception has occurred: ' + e.getMessage());
        }
    }
    public static void deactivatePlayers(List<Id> playersIds){
        List<Player__c> retPlayer = new List<Player__c>([SELECT id, Name, Email__c, Team__c, IsActive__c FROM Player__c WHERE id =: playersIds]);
        for (Player__c tmp : retPlayer) {
            tmp.IsActive__c=False;
        }
        try {
            upsert retPlayer;
        } catch (DmlException e) {
            System.debug('A DML upsert exception has occurred: ' + e.getMessage());
        }
    }
    class ScoreHelper{
        ScoreHelper(id tmpId, Integer tmpHomeTeamScore, Integer tmpVisitorsTeamScore){
            matchId=tmpId;
            homeTeamScore=tmpHomeTeamScore;
            visitorsTeamScore=tmpVisitorsTeamScore;
        }
        Id matchId;
        Integer homeTeamScore;
        Integer visitorsTeamScore;
       }
}