force-app/main/default/objects/Match__c/Match__c.object-meta.xml
<CustomObject>
    <description>Soccer match</description>
    <label>Match</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Match</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Match__c/fields/Home_Team__c.field-meta.xml
<CustomField>
    <fullName>Home_Team__c</fullName>
    <description>Home Team</description>
    <label>Home Team</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team must have 11 active players</errorMessage>
        <filterItems>
            <field>Team__c.Total_Active_Players__c</field>
            <operation>greaterOrEqual</operation>
            <value>11</value>
        </filterItems>
        <infoMessage>Team must have 11 active players</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Match</relationshipLabel>
    <relationshipName>Match</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <defaultValue>&apos;0:0&apos;</defaultValue>
    <description>Represents Home Team vs Visitor scores (e.g. &apos;1:2&apos; means Visitor won)</description>
    <label>Score</label>
    <length>5</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Start_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Start_DateTime__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>Beginning of the match</description>
    <label>Start DateTime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Match__c/fields/Visitors__c.field-meta.xml
<CustomField>
    <fullName>Visitors__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Visitor team</description>
    <label>Visitor</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Team must have 11 active players</errorMessage>
        <filterItems>
            <field>Team__c.Total_Active_Players__c</field>
            <operation>greaterOrEqual</operation>
            <value>11</value>
        </filterItems>
        <infoMessage>Team must have 11 active players</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Match (Visitor)</relationshipLabel>
    <relationshipName>Match1</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Scheduler.cls
global class Scheduler implements Schedulable {
    public static String sched = '0 00 00 1 * ?';  //Every month start
    public Integer base=50; // base value of bonus for player
    global static String schedulerStart() {
        Scheduler SC = new Scheduler(); 
        return System.schedule('Bonus accured', sched, SC);
    }

    global void execute(SchedulableContext sc) {

        PlayerBonusBatch b1 = new PlayerBonusBatch(SoccerDAO.getTeamWins([SELECT id, score__c, Home_Team__c, Visitors__c FROM Match__c WHERE Start_Datetime__c=LAST_MONTH]),base);
        ID batchId = Database.executeBatch(b1);           
    }
}